package com.luisgarcializ.ensenyas.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryBlue = Color(0xFF2196F3) // Un azul vibrante
val PrimaryLightBlue = Color(0xFF64B5F6) // Un azul más claro
val PrimaryDarkBlue = Color(0xFF1976D2) // Un azul más oscuro

val SecondaryOrange = Color(0xFFFF9800) // Un naranja para acentos
val SecondaryLightOrange = Color(0xFFFFB74D)
val SecondaryDarkOrange = Color(0xFFF57C00)

val White = Color(0xFFFFFFFF)
val Black = Color(0xFF000000)
val Gray = Color(0xFFCCCCCC)
val DarkGray = Color(0xFF333333)

val md_theme_light_primary = Color(0xFF00639B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCCE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D33)
val md_theme_light_secondary = Color(0xFF53616F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD6E5F6)
val md_theme_light_onSecondaryContainer = Color(0xFF0F1E2A)
val md_theme_light_tertiary = Color(0xFF69597C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF0DBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF231735)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE4EA)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72787E)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3133)
val md_theme_light_inversePrimary = Color(0xFF90CCFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00639B)
val md_theme_light_outlineVariant = Color(0xFFC2C7CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF90CCFF)
val md_theme_dark_onPrimary = Color(0xFF003353)
val md_theme_dark_primaryContainer = Color(0xFF004B76)
val md_theme_dark_onPrimaryContainer = Color(0xFFCCE5FF)
val md_theme_dark_secondary = Color(0xFFBCC9D8)
val md_theme_dark_onSecondary = Color(0xFF25313F)
val md_theme_dark_secondaryContainer = Color(0xFF3B4857)
val md_theme_dark_onSecondaryContainer = Color(0xFFD6E5F6)
val md_theme_dark_tertiary = Color(0xFFD6BBF4)
val md_theme_dark_onTertiary = Color(0xFF392D4B)
val md_theme_dark_tertiaryContainer = Color(0xFF514263)
val md_theme_dark_onTertiaryContainer = Color(0xFFF0DBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CE)
val md_theme_dark_outline = Color(0xFF8C9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inversePrimary = Color(0xFF00639B)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF90CCFF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)
val VeryLightBlueButton = Color(0xFFF0F8FF)
val ScreenBackground = Color(0xFFF0F8FF) // Mantenemos este color para el fondo que no es degradado
val OffWhite = Color(0xFFF8F8F8) // Un blanco roto muy sutil
val LockedCardBackground = Color(0xFFE0EFFF)
val BackgroundGradientStart = Color(0xFFE7F1F8)
val BackgroundGradientEnd = Color(0xFFBAE5FF)

val VeryDarkBlue = Color(0xFF000066)
val seed = Color(0xFF2196F3)